[tool.poetry]
name = "fastapi-utils"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["David Montague <davwmont@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

fastapi = "*"
pydantic = "^1.0"
sqlalchemy = "^1.3.12"

[tool.poetry.dev-dependencies]
# Starlette features
aiofiles = "*"  # Serving static files
requests = "*"  # TestClient

# Testing
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
coverage = "*"

# Static
isort = "*"
autoflake = "*"
black = { version = "*", allow-prereleases = true }
flake8 = "*"
mypy = "*"
sqlalchemy-stubs = "*"

# Documentation
mkdocs = "*"
mkdocs-material = "*"
markdown-include = "*"

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | build
  )/
)
'''

[tool.isort]
line_length = 120
known_first_party = ["fastapi-utils", "tests"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
